config/routes.rb
Rails.application.routes.draw do
  root 'chords#index'
  resources :chords
  # root 'static_pages#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chord.rb
class Chord < ApplicationRecord
end

app/models/scraping.rb
# require 'mechanize'
# require 'activerecord-import'

class Scraping < ApplicationRecord
  
  HTTPS                 = 'https:'
  LINK_0_DIR            = '//music.j-total.net/sp/as/'
  LINK_2_DIR            = '//music.j-total.net/dbsp/'
  ERRMSG_GET_REQ        = 'GETリクエストエラー発生'
  XPATH_LINK_0          = '/html/body/table[4]/tr/td/div/a'
  XPATH_LINK_1          = '/html/body/ul[3]/li/a'
  XPATH_LINK_2          = '/html/body/table[6]/tr/td/div/form/p/a[@target=""]'
  XPATH_LINK_2_NEXT     = '/html/body/center[3]/font/a'
  XPATH_LINK_2_NEXT_2   = '/html/body/center[3]/font/a[2]'
  # XPATH_LINK_3_CHORDS   = '/html/body/table[4]/tr/td[1]/table/tr/td/table/tr[2 or 3]/td/table/tr/td/div/div[2]/tt/a'
  # XPATH_LINK_3_CHORDS   = '/html/body/table[4]/tr/td[1]/table/tr/td/table/tr[3]/td/table/tr/td/tt/a'
  XPATH_LINK_3_CHORDS   = '/html/body/table[4]/tr/td[1]/table/tr/td/table/tr[2 or 3]/td/table/tr/td//tt/a'
  # XPATH_LINK_3_CHORDS_2 = '/html/body/div[3]/div[1]/p[1]/tt/a'
  # XPATH_LINK_3_CHORDS_2 = '/html/body/div[3]/div[1]/tt/a'
  XPATH_LINK_3_CHORDS_2 = '/html/body/div[3]/div[1]//tt/a'
  
  # 指定リンクにGETリクエスト
  # エラーの場合、エラーメッセージ出力
  def self.get_request(agent, link)
    url = link.start_with?('https:') ? link : HTTPS + link
    url = url.delete("\n")
    agent.get(url)
  rescue
    puts ERRMSG_GET_REQ
    puts url
    puts ''
  end
  
  # 指定XPathのリンクを配列で取得
  def self.get_child_links(page, xpath)
    links      = []
    links_text = []
    if page
      elements = page / xpath
      elements&.each { |e|
        links      << e[:href]
        links_text << e.inner_text
      }
    end
    return links, links_text
  end
  
  def self.scrape
    agent = Mechanize.new
  
    # アーティスト別検索ページから、あいうえお順検索結果ページのリンクを取得
    page = get_request(agent, LINK_0_DIR)
    links_1 = get_child_links(page, XPATH_LINK_0)
    
    links_1[0][0..1].uniq.each do |link_1|
      # あいうえお順検索結果ページから、アーティスト名検索結果ページのリンクを取得
      page = get_request(agent, link_1)
      links_2 = get_child_links(page, XPATH_LINK_1)
      
      links_2[0].each_with_index do |link_2, index_links_2|
        song_chords = []
        
        # アーティスト名検索結果ページから、楽曲コード譜ページのリンクを取得
        page = get_request(agent, link_2)
        links_3 = get_child_links(page, XPATH_LINK_2)
        
        # 次ページのリンクがある場合、次ページから楽曲コード譜ページのリンクを追加で取得
        if element_next = page&.at(XPATH_LINK_2_NEXT)
          link_next = element_next[:href]
          page = get_request(agent, LINK_2_DIR + link_next)
          links_3_add = get_child_links(page, XPATH_LINK_2)
          links_3[0] += links_3_add[0]
          links_3[1] += links_3_add[1]
          
          while element_next = page&.at(XPATH_LINK_2_NEXT_2)
            link_next = element_next[:href]
            page = get_request(agent, LINK_2_DIR + link_next)
            links_3_add = get_child_links(page, XPATH_LINK_2)
            links_3[0] += links_3_add[0]
            links_3[1] += links_3_add[1]
          end
        end
        
        links_3[0].each_with_index do |link_3, index_links_3|
          # 楽曲コード譜ページから、データベースに保存する情報（曲名、アーティスト名、コード）を取得
          page = get_request(agent, link_3)
          if page
            # 曲名を取得
            #chord.song = links_3[1][index_links_3]
            song = links_3[1][index_links_3]
            
            # アーティスト名を取得
            artist_lines = links_2[1][index_links_2]
            artist = ''
            artist_lines.each_line { |l| artist += l.lstrip }
            # chord.artist = artist.delete("\n")
            artist = artist.delete("\n")
            
            # chord = Chord.new
            song_chord = Chord.where(song: song, artist: artist).first_or_initialize
            
            # 楽曲コード譜ページURLを取得
            song_chord.page_url = page.uri.to_s
            
            puts "#{DateTime.now.minute}:#{DateTime.now.second}"
            
            chords = page / XPATH_LINK_3_CHORDS
            chords = page / XPATH_LINK_3_CHORDS_2 if chords.empty?
            if chords.empty?
              puts "\n\n\n******************\n\n\nコード無い\n#{link_3}\n\n\n******************\n\n\n"
            end
            puts song_chord.chords = chords.inner_text
            
            song_chords << song_chord
          end
        end
        Chord.import(song_chords, on_duplicate_key_update: %i(song artist page_url chords))
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chords_controller.rb
class ChordsController < ApplicationController
  before_action :set_chord, only: %i[ show edit update destroy ]

  YOUTUBE_URL = 'https://www.youtube.com/results?search_query='
  SPOTIFY_URL = 'https://open.spotify.com/search/'

  # GET /chords or /chords.json
  def index
    # @chords = Chord.all
    @q = Chord.ransack(params[:q])
    @chords = @q.result(distinct: true).page(params[:page])
    @youtube_url = YOUTUBE_URL
    @spotify_url = SPOTIFY_URL
  end

  # GET /chords/1 or /chords/1.json
  def show
  end

  # GET /chords/new
  def new
    @chord = Chord.new
  end

  # GET /chords/1/edit
  def edit
  end

  # POST /chords or /chords.json
  def create
    @chord = Chord.new(chord_params)

    respond_to do |format|
      if @chord.save
        format.html { redirect_to @chord, notice: "Chord was successfully created." }
        format.json { render :show, status: :created, location: @chord }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chord.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chords/1 or /chords/1.json
  def update
    respond_to do |format|
      if @chord.update(chord_params)
        format.html { redirect_to @chord, notice: "Chord was successfully updated." }
        format.json { render :show, status: :ok, location: @chord }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chord.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chords/1 or /chords/1.json
  def destroy
    @chord.destroy
    respond_to do |format|
      format.html { redirect_to chords_url, notice: "Chord was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chord
      @chord = Chord.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chord_params
      params.require(:chord).permit(:song, :artist, :chords, :page_url)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = 'Chordex'
    if page_title.empty?
      base_title + ' | コード進行から曲を検索'
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/chords_helper.rb
module ChordsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/chords/_form.html.erb
<%= form_with(model: chord) do |form| %>
  <% if chord.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chord.errors.count, "error") %> prohibited this chord from being saved:</h2>

      <ul>
        <% chord.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :song %>
    <%= form.text_field :song %>
  </div>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist %>
  </div>

  <div class="field">
    <%= form.label :chords %>
    <%= form.text_field :chords %>
  </div>

  <div class="field">
    <%= form.label :page_url %>
    <%= form.text_field :page_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chords/edit.html.erb
<h1>Editing Chord</h1>

<%= render 'form', chord: @chord %>

<%= link_to 'Show', @chord %> |
<%= link_to 'Back', chords_path %>

app/views/chords/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="search-form">
    <%= search_form_for @q do |f| %>
      <div class="form-row">
        <%= f.label :chords_cont, '楽曲コード', id: 'label-chords' %>
        <% (1..4).each do |n| %>
          <div class="formgroup col-md-3">
            <select id="chord<%= n %>" class="form-control" onchange="clickBtn()">
              <option value="">-</option>
              <% roots = ['C', 'C#', 'D♭', 'D', 'D#', 'E♭', 'E', 'F', 'F#', 'G♭', 'G', 'G#', 'A♭', 'A', 'A#', 'B♭', 'B'] %>
              <% roots.each do |r| %>
                <option value="<%= r %>"><%= r %></option>
                <option value="<%= r %>7"><%= r %>7</option>
                <option value="<%= r %>m"><%= r %>m</option>
                <option value="<%= r %>m7"><%= r %>m7</option>
                <option value="<%= r %>M7"><%= r %>M7</option>
                <option value="<%= r %>sus4"><%= r %>sus4</option>
                <option value="<%= r %>dim"><%= r %>dim</option>
              <% end %>
            </select>
          </div>
        <% end %>

        <script>
          const c1 = localStorage.getItem('selectedIndex_c1');
          const c2 = localStorage.getItem('selectedIndex_c2');
          const c3 = localStorage.getItem('selectedIndex_c3');
          const c4 = localStorage.getItem('selectedIndex_c4');
          document.getElementById('chord1').options[c1].selected = true;
          document.getElementById('chord2').options[c2].selected = true;
          document.getElementById('chord3').options[c3].selected = true;
          document.getElementById('chord4').options[c4].selected = true;

          function clickBtn() {
            const select_c1 = document.getElementById('chord1');
            const select_c2 = document.getElementById('chord2');
            const select_c3 = document.getElementById('chord3');
            const select_c4 = document.getElementById('chord4');
            const chords = select_c1.value + select_c2.value + select_c3.value + select_c4.value;
            document.getElementById('q_chords_cont').setAttribute('value', chords);

            localStorage.setItem('selectedIndex_c1', select_c1.selectedIndex);
            localStorage.setItem('selectedIndex_c2', select_c2.selectedIndex);
            localStorage.setItem('selectedIndex_c3', select_c3.selectedIndex);
            localStorage.setItem('selectedIndex_c4', select_c4.selectedIndex);
          }
        </script>

        <%= f.search_field :chords_cont %>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <%= f.label :song_cont, '曲名' %>
          <%= f.search_field :song_cont, class: 'form-control', placeholder: "曲名を入力..." %>
        </div>
        <div class="form-group col-md-6">
          <%= f.label :artist_cont, '歌手名' %>
          <%= f.search_field :artist_cont, class: 'form-control', placeholder: "歌手名を入力..." %>
        </div>
        <%= f.submit '検索', class: 'form-group btn btn-primary' %>
      </div>
    <% end %>
  </div>
  <div>
    <%= paginate @chords %>
    <table class="table table-striped table-hover">
      <thead class="">
        <tr>
          <th scope="col"><%= sort_link(@q, :song, '曲名', default_order: :asc) %></th>
          <th scope="col"><%= sort_link(@q, :artist, '歌手名', default_order: :asc) %></th>
          <th scope="col">YouTube</th>
          <th scope="col">Spotify</th>
          <th scope="col" colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @chords.each do |chord| %>
          <tr>
            <th scope="row" width="36%"><%= link_to(chord.song, chord.page_url) %></th>
            <td width="28%"><%= chord.artist %></td>
            <td>
              <%= link_to(image_tag('youtube.svg', width: '25'), @youtube_url + chord.song + '+' + chord.artist) %>
            </td>
            <td>
              <%= link_to(image_tag('spotify.svg', width: '25'), @spotify_url + chord.song + '%20' + chord.artist) %>
            </td>
            <td><%= link_to '閲覧', chord %></td>
            <td><%= link_to '編集', edit_chord_path(chord) %></td>
            <td><%= link_to '削除', chord, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @chords %>
  </div>

  <br>

  <%= link_to '新規作成', new_chord_path %>
</div>

app/views/chords/new.html.erb
<h1>New Chord</h1>

<%= render 'form', chord: @chord %>

<%= link_to 'Back', chords_path %>

app/views/chords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Song:</strong>
  <%= @chord.song %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @chord.artist %>
</p>

<p>
  <strong>Chords:</strong>
  <%= @chord.chords %>
</p>

<p>
  <strong>Page url:</strong>
  <%= @chord.page_url %>
</p>

<%= link_to 'Edit', edit_chord_path(@chord) %> |
<%= link_to 'Back', chords_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>Chordex</small>
  <nav>
    <ul>
      <li>&copy; 2021 Kuboki</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to('Chordex', '/', id: 'logo') %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to('保存リスト', '#') %></li>
        <li><%= link_to('ログイン', '#') %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/head' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <%= yield %>
    <div class="container">
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/top.html.erb
<!-- <% provide(:title, ) %> -->
<main>
  <div class="center jumbotron">
    <div class="container">
      <p class="title">
        J-POPの有名曲を、<br>
        好きなコード進行で検索。
      </p>
      <p class="description">
        覚えたコードで他の曲が弾き語りできたり、<br>
        作曲や編曲のアイデアに活用したり。<br>
        好きな4つのコードで検索を開始できます。
      </p>
    </div>
  </div>
</main>